apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
data:
  user: dW5ieGQ=
  password: cG9zdGdyZXM=
  site-key: ZGVtby11bmJ4ZDcwMDE4MTUwMzU3NjU1OA==
  unbxd-api-key: ZmI4NTNlMzMzMmYyNjQ1ZmFjOWQ3MWRjNjNlMDllYzE=